services:
  - type: web
    name: elicit-25-backend
    rootDir: server
    runtime: node
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
    buildCommand: npm ci
    startCommand: npm run start
    autoDeploy: true